Repository CodeFlow201/forestTreesTagging, pull requests merged in 2021-03, with the labels that each got.

#25 Tech stack
  README.md
Labels: GSSOC21, Level1

#27 Created Contributing.md file
  Contributing.md
  lib/components/logIn.dart
  pubspec.lock
Labels: GSSOC21, Level1

#28 [QA] Added issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general_issue.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GSSOC21, Level1, documentation, good first issue

#34 [label] Add: workflow for gssoc auto label
  .github/workflows/autoLabel.yml
Labels: GSSOC21, Level1

#42 Added automatic location detection
  .gradle/6.1.1/executionHistory/executionHistory.lock
  android/app/src/main/AndroidManifest.xml
  lib/components/generatorPage.dart
  local.properties
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level2
