Repository CodeFlow201/forestTreesTagging, pull requests merged in 2021-04, with the labels that each got.

#64 fixed issue#62
  lib/components/signUp.dart
  pubspec.lock
Labels: GSSOC21, Level2

#68 issue-41 fixed
  lib/components/treeInfoPage.dart
  lib/components/treeListItem.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level2

#70 Changed the design of scanned tree list
  lib/components/scannerPage.dart
  lib/components/treeListItem.dart
Labels: GSSOC21, Level2

#76 Update README.md
  README.md
Labels: GSSOC21, Level1

#78 Forgot Password Feature Added
  lib/components/logIn.dart
Labels: GSSOC21, Level3

#82 refactored profile image storing and retrieving method
  lib/Services/dbUserData.dart
  lib/Services/firebaseStroageService.dart
  lib/Services/googleAuthentication.dart
  lib/Services/signUpAuthentication.dart
  lib/components/homeScreen.dart
  lib/components/logIn.dart
  pubspec.yaml
Labels: GSSOC21, Level2
